name: dual_screen_samples
description: Showcases dual screen design patterns in Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.3
  google_fonts: ^2.0.0
  flutter_markdown: ^0.6.2
  flutter_map: ^0.12.0
  dual_screen:
    path: ../dual_screen

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/list_detail/
    - images/dual_view_restaurants/
